### ISSUE TITLE
Crash with Chopper

### ISSUE THREAD

**Issue by twothe** [Vanhal/ProgressiveAutomation#200]
When using the chopper on a standard oak tree with standard stone axe it crashes occasionally with a NullPointerException while cutting the tree. After reload the issue does not happen again, so it is not reproducible.

Running ProgressiveAutomation-1.7.10-1.6.29 on Forge 10.13.4.1614 (1.7.10). No Thaumcraft installed.

Content of the machine after world reload:
![content](https://cloud.githubusercontent.com/assets/1131621/12102775/8bf13d68-b33d-11e5-932d-ec5f29983916.png)

    java.lang.NullPointerException: Ticking block entity
	at net.minecraft.item.ItemStack.func_77977_a(ItemStack.java:361)
	at com.vanhal.progressiveautomation.compat.mods.ThaumCraft.isLeaf(ThaumCraft.java:23)
	at com.vanhal.progressiveautomation.compat.ModHelper.isLeaf(ModHelper.java:85)
	at com.vanhal.progressiveautomation.entities.chopper.TileChopper.testBlock(TileChopper.java:372)
	at com.vanhal.progressiveautomation.entities.chopper.TileChopper.validBlock(TileChopper.java:335)
	at com.vanhal.progressiveautomation.entities.chopper.TileChopper.validBlock(TileChopper.java:330)
	at com.vanhal.progressiveautomation.entities.chopper.TileChopper.searchTree(TileChopper.java:308)
	at com.vanhal.progressiveautomation.entities.chopper.TileChopper.searchTree(TileChopper.java:318)
	at com.vanhal.progressiveautomation.entities.chopper.TileChopper.searchTree(TileChopper.java:318)
	at com.vanhal.progressiveautomation.entities.chopper.TileChopper.searchTree(TileChopper.java:318)
	at com.vanhal.progressiveautomation.entities.chopper.TileChopper.searchTree(TileChopper.java:318)
	at com.vanhal.progressiveautomation.entities.chopper.TileChopper.searchTree(TileChopper.java:318)
	at com.vanhal.progressiveautomation.entities.chopper.TileChopper.searchTree(TileChopper.java:318)
	at com.vanhal.progressiveautomation.entities.chopper.TileChopper.searchTree(TileChopper.java:318)
	at com.vanhal.progressiveautomation.entities.chopper.TileChopper.searchTree(TileChopper.java:318)
	at com.vanhal.progressiveautomation.entities.chopper.TileChopper.searchTree(TileChopper.java:318)
	at com.vanhal.progressiveautomation.entities.chopper.TileChopper.searchTree(TileChopper.java:318)
	at com.vanhal.progressiveautomation.entities.chopper.TileChopper.searchTree(TileChopper.java:318)
	at com.vanhal.progressiveautomation.entities.chopper.TileChopper.searchTree(TileChopper.java:318)
	at com.vanhal.progressiveautomation.entities.chopper.TileChopper.searchTree(TileChopper.java:318)
	at com.vanhal.progressiveautomation.entities.chopper.TileChopper.searchTree(TileChopper.java:318)
	at com.vanhal.progressiveautomation.entities.chopper.TileChopper.searchTree(TileChopper.java:318)
	at com.vanhal.progressiveautomation.entities.chopper.TileChopper.searchTree(TileChopper.java:318)
	at com.vanhal.progressiveautomation.entities.chopper.TileChopper.searchTree(TileChopper.java:318)
	at com.vanhal.progressiveautomation.entities.chopper.TileChopper.searchTree(TileChopper.java:318)
	at com.vanhal.progressiveautomation.entities.chopper.TileChopper.searchTree(TileChopper.java:318)
	at com.vanhal.progressiveautomation.entities.chopper.TileChopper.searchTree(TileChopper.java:318)
	at com.vanhal.progressiveautomation.entities.chopper.TileChopper.searchTree(TileChopper.java:318)
	at com.vanhal.progressiveautomation.entities.chopper.TileChopper.searchTree(TileChopper.java:318)
	at com.vanhal.progressiveautomation.entities.chopper.TileChopper.findTree(TileChopper.java:301)
	at com.vanhal.progressiveautomation.entities.chopper.TileChopper.scanBlocks(TileChopper.java:184)
	at com.vanhal.progressiveautomation.entities.chopper.TileChopper.readyToBurn(TileChopper.java:388)
	at com.vanhal.progressiveautomation.entities.BaseTileEntity.func_145845_h(BaseTileEntity.java:331)
	at com.vanhal.progressiveautomation.entities.UpgradeableTileEntity.func_145845_h(UpgradeableTileEntity.java:183)
	at com.vanhal.progressiveautomation.entities.chopper.TileChopper.func_145845_h(TileChopper.java:156)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by twothe** [comment]
I had the chopper placed right on the chunk border. Maybe it tried to harvest from unloaded chunks?

**Comment by twothe** [comment]
I put the chopper in the center of the chunk but that did not solve the issue. Next guess is that a leaf block in between decays on its own and the chopper is not double-checking that.
