### ISSUE TITLE
Crash when piping out of planter

### ISSUE THREAD

**Issue by guardianzozo** [Vanhal/ProgressiveAutomation#210]
Dont know if it makes a difference but enviromine decay is on and we are using Agricraft as well (and piping out using Mekanism pipes)

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2/18/16 8:18 PM
Description: Ticking block entity

java.lang.ClassCastException: net.minecraft.item.ItemReed cannot be cast to com.vanhal.progressiveautomation.items.upgrades.ItemUpgrade
    at com.vanhal.progressiveautomation.entities.UpgradeableTileEntity.func_145845_h(UpgradeableTileEntity.java:189)
    at com.vanhal.progressiveautomation.entities.planter.TilePlanter.func_145845_h(TilePlanter.java:57)
    at net.minecraft.world.World.func_72939_s(World.java:1939)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at com.vanhal.progressiveautomation.entities.UpgradeableTileEntity.func_145845_h(UpgradeableTileEntity.java:189)
    at com.vanhal.progressiveautomation.entities.planter.TilePlanter.func_145845_h(TilePlanter.java:57)

-- Block entity being ticked --
Details:
    Name: TilePlanterDiamond // com.vanhal.progressiveautomation.entities.planter.TilePlanterDiamond
    Block type: ID #2819 (tile.PlanterDiamond // com.vanhal.progressiveautomation.blocks.BlockPlanter)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (1332,39,3208), Chunk: (at 4,2,8 in 83,200; contains blocks 1328,0,3200 to 1343,255,3215), Region: (2,6; contains chunks 64,192 to 95,223, blocks 1024,0,3072 to 1535,255,3583)
    Actual block type: ID #2819 (tile.PlanterDiamond // com.vanhal.progressiveautomation.blocks.BlockPlanter)
    Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1939)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

**Comment by Vanhal** [comment]
Version?

**Comment by guardianzozo** [comment]
Version 1.6.29 for 1.7.10

**Comment by Vanhal** [comment]
Can you upgrade to the newest version, cause I'm sure I fixed that in one of the latest releases
