### ISSUE TITLE
Crash when inserting axe and infested leaves exist

### ISSUE THREAD

**Issue by Josephur** [Vanhal/ProgressiveAutomation#221]
When infesting a lot of leaves and collecting most of them (but not all), reinserting axe back into chopper seems to crash it.

[16:40:03] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:642) ~[MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 8
    at exnihilo.blocks.itemBlocks.ItemBlockLeavesInfested.func_77667_c(ItemBlockLeavesInfested.java:19) ~[ItemBlockLeavesInfested.class:?]
    at net.minecraft.item.ItemStack.func_77977_a(ItemStack.java:361) ~[add.class:?]
    at com.vanhal.progressiveautomation.compat.mods.ThaumCraft.isLeaf(ThaumCraft.java:23) ~[ThaumCraft.class:?]
    at com.vanhal.progressiveautomation.compat.ModHelper.isLeaf(ModHelper.java:85) ~[ModHelper.class:?]
    at com.vanhal.progressiveautomation.entities.chopper.TileChopper.testBlock(TileChopper.java:372) ~[TileChopper.class:?]
    at com.vanhal.progressiveautomation.entities.chopper.TileChopper.validBlock(TileChopper.java:335) ~[TileChopper.class:?]
    at com.vanhal.progressiveautomation.entities.chopper.TileChopper.validBlock(TileChopper.java:330) ~[TileChopper.class:?]
    at com.vanhal.progressiveautomation.entities.chopper.TileChopper.searchTree(TileChopper.java:308) ~[TileChopper.class:?]
    at com.vanhal.progressiveautomation.entities.chopper.TileChopper.searchTree(TileChopper.java:318) ~[TileChopper.class:?]
    at com.vanhal.progressiveautomation.entities.chopper.TileChopper.searchTree(TileChopper.java:318) ~[TileChopper.class:?]
    at com.vanhal.progressiveautomation.entities.chopper.TileChopper.searchTree(TileChopper.java:318) ~[TileChopper.class:?]
    at com.vanhal.progressiveautomation.entities.chopper.TileChopper.searchTree(TileChopper.java:318) ~[TileChopper.class:?]
    at com.vanhal.progressiveautomation.entities.chopper.TileChopper.searchTree(TileChopper.java:318) ~[TileChopper.class:?]
    at com.vanhal.progressiveautomation.entities.chopper.TileChopper.searchTree(TileChopper.java:318) ~[TileChopper.class:?]
    at com.vanhal.progressiveautomation.entities.chopper.TileChopper.searchTree(TileChopper.java:318) ~[TileChopper.class:?]
    at com.vanhal.progressiveautomation.entities.chopper.TileChopper.searchTree(TileChopper.java:323) ~[TileChopper.class:?]
    at com.vanhal.progressiveautomation.entities.chopper.TileChopper.searchTree(TileChopper.java:318) ~[TileChopper.class:?]
    at com.vanhal.progressiveautomation.entities.chopper.TileChopper.searchTree(TileChopper.java:318) ~[TileChopper.class:?]
    at com.vanhal.progressiveautomation.entities.chopper.TileChopper.findTree(TileChopper.java:301) ~[TileChopper.class:?]
    at com.vanhal.progressiveautomation.entities.chopper.TileChopper.scanBlocks(TileChopper.java:184) ~[TileChopper.class:?]
    at com.vanhal.progressiveautomation.entities.chopper.TileChopper.readyToBurn(TileChopper.java:388) ~[TileChopper.class:?]
    at com.vanhal.progressiveautomation.entities.BaseTileEntity.func_145845_h(BaseTileEntity.java:331) ~[BaseTileEntity.class:?]
    at com.vanhal.progressiveautomation.entities.UpgradeableTileEntity.func_145845_h(UpgradeableTileEntity.java:192) ~[UpgradeableTileEntity.class:?]
    at com.vanhal.progressiveautomation.entities.chopper.TileChopper.func_145845_h(TileChopper.java:156) ~[TileChopper.class:?]
    at net.minecraft.world.World.func_72939_s(World.java:1939) ~[ahb.class:?]
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) ~[mt.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) ~[MinecraftServer.class:?]
    ... 4 more

**Comment by Josephur** [comment]
Also this has permanently glitched the map as every time the server restarts, it does the same.  Having to use MCEdit to fix the world now :(

**Comment by Vanhal** [comment]
What version are you running?
