### ISSUE TITLE
NullPointer in Chopper Crashing Server

### ISSUE THREAD

**Issue by jfs** [Vanhal/ProgressiveAutomation#222]
java.lang.NullPointerException: Ticking block entity
	at net.minecraft.item.ItemStack.func_77977_a(ItemStack.java:361)
	at com.vanhal.progressiveautomation.compat.mods.ThaumCraft.isLeaf(ThaumCraft.java:23)
	at com.vanhal.progressiveautomation.compat.ModHelper.isLeaf(ModHelper.java:85)
	at com.vanhal.progressiveautomation.entities.chopper.TileChopper.testBlock(TileChopper.java:372)
	at com.vanhal.progressiveautomation.entities.chopper.TileChopper.validBlock(TileChopper.java:335)
	at com.vanhal.progressiveautomation.entities.chopper.TileChopper.validBlock(TileChopper.java:330)
	at com.vanhal.progressiveautomation.entities.chopper.TileChopper.searchTree(TileChopper.java:308)
	at com.vanhal.progressiveautomation.entities.chopper.TileChopper.searchTree(TileChopper.java:318)
	at com.vanhal.progressiveautomation.entities.chopper.TileChopper.searchTree(TileChopper.java:318)
	at com.vanhal.progressiveautomation.entities.chopper.TileChopper.searchTree(TileChopper.java:318)
	at com.vanhal.progressiveautomation.entities.chopper.TileChopper.searchTree(TileChopper.java:318)
	at com.vanhal.progressiveautomation.entities.chopper.TileChopper.searchTree(TileChopper.java:318)
	at com.vanhal.progressiveautomation.entities.chopper.TileChopper.searchTree(TileChopper.java:318)
	at com.vanhal.progressiveautomation.entities.chopper.TileChopper.searchTree(TileChopper.java:318)
	at com.vanhal.progressiveautomation.entities.chopper.TileChopper.searchTree(TileChopper.java:318)
	at com.vanhal.progressiveautomation.entities.chopper.TileChopper.searchTree(TileChopper.java:318)
	at com.vanhal.progressiveautomation.entities.chopper.TileChopper.searchTree(TileChopper.java:318)
	at com.vanhal.progressiveautomation.entities.chopper.TileChopper.searchTree(TileChopper.java:318)
	at com.vanhal.progressiveautomation.entities.chopper.TileChopper.searchTree(TileChopper.java:318)
	at com.vanhal.progressiveautomation.entities.chopper.TileChopper.searchTree(TileChopper.java:318)
	at com.vanhal.progressiveautomation.entities.chopper.TileChopper.searchTree(TileChopper.java:318)
	at com.vanhal.progressiveautomation.entities.chopper.TileChopper.searchTree(TileChopper.java:318)
	at com.vanhal.progressiveautomation.entities.chopper.TileChopper.searchTree(TileChopper.java:318)
	at com.vanhal.progressiveautomation.entities.chopper.TileChopper.searchTree(TileChopper.java:318)
	at com.vanhal.progressiveautomation.entities.chopper.TileChopper.searchTree(TileChopper.java:318)
	at com.vanhal.progressiveautomation.entities.chopper.TileChopper.searchTree(TileChopper.java:318)
	at com.vanhal.progressiveautomation.entities.chopper.TileChopper.findTree(TileChopper.java:301)
	at com.vanhal.progressiveautomation.entities.chopper.TileChopper.scanBlocks(TileChopper.java:184)
	at com.vanhal.progressiveautomation.entities.chopper.TileChopper.readyToBurn(TileChopper.java:388)
	at com.vanhal.progressiveautomation.entities.BaseTileEntity.func_145845_h(BaseTileEntity.java:369)
	at com.vanhal.progressiveautomation.entities.UpgradeableTileEntity.func_145845_h(UpgradeableTileEntity.java:192)
	at com.vanhal.progressiveautomation.entities.chopper.TileChopper.func_145845_h(TileChopper.java:156)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by jfs** [comment]
In version 1.6.34

**Comment by dshadowwolf** [comment]
Same issue, 1.7.10 and Thaumcraft 4.

**Comment by dshadowwolf** [comment]
Oddly... None of the choppers are planting Thaumcraft trees and there are no Thaumcraft trees in range of the choppers. This might be why the crash is not occurring, but would not explain the crash overnight or the crash this morning after the restart.

**Comment by dshadowwolf** [comment]
On further inspection, I suspect that this is a bug in Thaumcraft. I've used the "Minecraft Coders Pack" to check some things and the function at the top of the heap (in net.minecraft.item.ItemStack) is dereferencing an internal field that appears to relate to the Item object itself that the stack is built from. 

The only fix I can see is a try-catch around the test that is causing this to trigger. I have a quick&dirty fix implementing this ready for testing - I'll push it to my private server. If that works, I'll make sure a pull request with this (admittedly hackish) fix goes out.

**Comment by dshadowwolf** [comment]
Did some more code reading and think that a real solution will require a refactor that gets a reference to the block being tested much earlier and passes it down rather than the coordinates to be tested. I'll cancel the earlier pull request and see about spinning up that refactor tomorrow. 

It seems, to me, that something is causing the item registry to return an invalid item when the ItemStack being passed to ModHelper.isLeaf() is created. That, in particular, looks to, possibly, be the root cause of this.

**Comment by Vanhal** [comment]
Change was added, thanks!
