### ISSUE TITLE
forge server 1.9 crashes on start

### ISSUE THREAD

**Issue by thegamezbeplayed** [Vanhal/ProgressiveAutomation#238]
i  only have progressive automation installed on the server

 ---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 4/21/16 5:10 PM
Description: Ticking block entity

java.lang.StringIndexOutOfBoundsException: String index out of range: 15
	at java.lang.String.substring(Unknown Source)
	at com.vanhal.progressiveautomation.ref.ToolHelper.tinkersType(ToolHelper.java:116)
	at com.vanhal.progressiveautomation.entities.BaseTileEntity.destroyTool(BaseTileEntity.java:497)
	at com.vanhal.progressiveautomation.entities.killer.TileKiller.func_73660_a(TileKiller.java:98)
	at net.minecraft.world.World.func_72939_s(World.java:1791)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:705)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:386)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:609)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:467)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.lang.String.substring(Unknown Source)
	at com.vanhal.progressiveautomation.ref.ToolHelper.tinkersType(ToolHelper.java:116)
	at com.vanhal.progressiveautomation.entities.BaseTileEntity.destroyTool(BaseTileEntity.java:497)
	at com.vanhal.progressiveautomation.entities.killer.TileKiller.func_73660_a(TileKiller.java:98)

-- Block entity being ticked --
Details:
	Name: TileKillerIron // com.vanhal.progressiveautomation.entities.killer.TileKillerIron
	Block type: ID #239 (tile.KillerIron // com.vanhal.progressiveautomation.blocks.BlockKiller)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (23,69,293), Chunk: (at 7,4,5 in 1,18; contains blocks 16,0,288 to 31,255,303), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #239 (tile.KillerIron // com.vanhal.progressiveautomation.blocks.BlockKiller)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1791)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['Grandsmith'/73556, l='world', x=-28.51, y=78.00, z=318.55]]
	Chunk stats: ServerChunkCache: 457 Drop: 0
	Level seed: -3344995452341806823
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-64,64,256), Chunk: (at 0,4,0 in -4,16; contains blocks -64,0,256 to -49,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 12846116 game time, 12846116 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 99393 (now: false), thunder time: 236 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:705)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:386)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:609)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:467)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.9
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_73, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 877453856 bytes (836 MB) / 1121976320 bytes (1070 MB) up to 1886912512 bytes (1799 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.23 Powered by Forge 12.16.0.1865 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.9-12.16.0.1865-1.9-universal.jar) 
	UCHIJAAAA	Forge{12.16.0.1865} [Minecraft Forge] (forge-1.9-12.16.0.1865-1.9-universal.jar) 
	UCHIJAAAA	progressiveautomation{1.6.41} [Progressive Automation] (ProgressiveAutomation-1.9-1.6.41.jar) 
	Loaded coremods (and transformers): 
	Profiler Position: N/A (disabled)
	Player Count: 2 / 20; [EntityPlayerMP['Wegra310'/5659, l='world', x=-58.49, y=72.00, z=20.65], EntityPlayerMP['Grandsmith'/73556, l='world', x=-28.51, y=78.00, z=318.55]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by thegamezbeplayed** [comment]
i suspect my killer has just broken its weapon?, it apppears to be checking if i have tinker weapon. I do not have tinkers construct.

**Comment by thegamezbeplayed** [comment]
i got around the issue by copying my world over to single player and removing the fuel and weapon from my killer.
hope you can find a permanant fix!

**Comment by Vanhal** [comment]
That should fix it.

**Comment by thegamezbeplayed** [comment]
where do your most recent updates go?

**Comment by Vanhal** [comment]
http://mods.curse.com/mc-mods/minecraft/220606-progressive-automation-early-miner
