### ISSUE TITLE
My game crashed when i put coal into wooden generator. 1.9.4

### ISSUE THREAD

**Issue by awrexas** [Vanhal/ProgressiveAutomation#248]
FULL game output :

2016-05-29 05:25:01,691 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2016-05-29 05:25:01,692 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[05:25:01] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[05:25:01] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[05:25:01] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[05:25:01] [main/INFO] [FML]: Forge Mod Loader version 12.17.0.1922 for Minecraft 1.9.4 loading
[05:25:01] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_77, running on Windows 8.1:amd64:6.3, installed at C:\Program Files\Java\jre1.8.0_77
[05:25:01] [main/WARN] [FML]: The coremod com.olafski.fastleafdecay.FldLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[05:25:01] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[05:25:01] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[05:25:01] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[05:25:01] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[05:25:01] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[05:25:03] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[05:25:03] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[05:25:03] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[05:25:03] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[05:25:04] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
2016-05-29 05:25:04,040 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2016-05-29 05:25:04,056 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2016-05-29 05:25:04,071 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[05:25:04] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[05:25:04] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[05:25:04] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[05:25:04] [Client thread/INFO]: Setting user: Awrexas
[05:25:05] [Client thread/INFO] [FastLeafDecay]: Patching leaves.
[05:25:05] [Client thread/INFO] [FastLeafDecay]: Found Leave Class: net/minecraft/block/BlockLeaves
[05:25:07] [Client thread/INFO]: LWJGL Version: 2.9.4
[05:25:08] [Client thread/INFO] [STDOUT]: [net.minecraftforge.fml.client.SplashProgress:start:200]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  FldLoadingPlugin (FastLeafDecay-MC1.9.4-1.7.jar)
Contact their authors BEFORE contacting forge

// Would you like a cupcake?

Time: 29.05.16 05:25
Description: Loading screen debug info

This is just a prompt for computer specs to be printed. THIS IS NOT A ERROR

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.9.4
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_77, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 115470576 bytes (110 MB) / 270573568 bytes (258 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
FldLoadingPlugin (FastLeafDecay-MC1.9.4-1.7.jar)
  com.olafski.fastleafdecay.FldTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13431 Compatibility Profile Context 16.150.2211.0' Renderer: 'AMD Radeon HD 7900 Series'
[05:25:08] [Client thread/INFO] [FML]: MinecraftForge v12.17.0.1922 Initialized
[05:25:08] [Client thread/INFO] [FML]: Replaced 232 ore recipes
[05:25:09] [Client thread/INFO] [FML]: Found 0 mods from the command line. Injecting into mod discoverer
[05:25:09] [Client thread/INFO] [FML]: Searching C:\Users\ADMIN\AppData\Roaming\.minecraft\mods for mods
[05:25:10] [Client thread/INFO] [FML]: Forge Mod Loader has identified 6 mods to load
[05:25:10] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, fastleafdecay, playerstats, progressiveautomation] at CLIENT
[05:25:10] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, fastleafdecay, playerstats, progressiveautomation] at SERVER
[05:25:11] [Client thread/INFO] [progressiveautomation]: Starting automation
[05:25:11] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Fast Leaf Decay, FMLFileResourcePack:Player Stats, FMLFileResourcePack:Progressive Automation, S&K Photo Realism x256 (v0.4.2b).zip
[05:25:11] [Client thread/INFO] [FML]: Processing ObjectHolder annotations
[05:25:11] [Client thread/INFO] [FML]: Found 418 ObjectHolder annotations
[05:25:11] [Client thread/INFO] [FML]: Identifying ItemStackHolder annotations
[05:25:11] [Client thread/INFO] [FML]: Found 0 ItemStackHolder annotations
[05:25:11] [Client thread/INFO] [FML]: Configured a dormant chunk cache size of 0
[05:25:11] [Forge Version Check/INFO] [ForgeVersionCheck]: [Forge] Starting version check at http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[05:25:11] [Client thread/INFO] [progressiveautomation]: MFR Loaded
[05:25:11] [Client thread/INFO] [progressiveautomation]: RightClickPlants Loaded
[05:25:11] [Client thread/INFO] [progressiveautomation]: Vanilla Loaded
[05:25:11] [Forge Version Check/INFO] [ForgeVersionCheck]: [Forge] Found status: BETA_OUTDATED Target: 12.17.0.1926
[05:25:11] [Client thread/INFO] [FML]: Applying holder lookups
[05:25:11] [Client thread/INFO] [FML]: Holder lookups applied
[05:25:11] [Client thread/INFO] [FML]: Injecting itemstacks
[05:25:11] [Client thread/INFO] [FML]: Itemstack injection complete
[05:25:12] [Sound Library Loader/INFO]: Starting up SoundSystem...
[05:25:12] [Thread-8/INFO]: Initializing LWJGL OpenAL
[05:25:12] [Thread-8/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[05:25:12] [Thread-8/INFO]: OpenAL initialized.
[05:25:13] [Sound Library Loader/INFO]: Sound engine started
[05:25:14] [Client thread/INFO] [FML]: Max texture size: 16384
[05:25:14] [Client thread/INFO]: Created: 16x16 textures-atlas
[05:25:15] [Client thread/INFO] [Player Stats]: Model definition for location playerstats:stats_book:0
[05:25:15] [Client thread/INFO] [FML]: Injecting itemstacks
[05:25:15] [Client thread/INFO] [FML]: Itemstack injection complete
[05:25:15] [Client thread/INFO] [FML]: Forge Mod Loader has successfully loaded 6 mods
[05:25:15] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Fast Leaf Decay, FMLFileResourcePack:Player Stats, FMLFileResourcePack:Progressive Automation, S&K Photo Realism x256 (v0.4.2b).zip
[05:25:16] [Client thread/INFO]: SoundSystem shutting down...
[05:25:16] [Client thread/WARN]: Author: Paul Lamb, www.paulscode.com
[05:25:16] [Sound Library Loader/INFO]: Starting up SoundSystem...
[05:25:16] [Thread-10/INFO]: Initializing LWJGL OpenAL
[05:25:16] [Thread-10/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[05:25:16] [Thread-10/INFO]: OpenAL initialized.
[05:25:16] [Sound Library Loader/INFO]: Sound engine started
[05:25:17] [Client thread/INFO] [FML]: Max texture size: 16384
[05:25:17] [Client thread/INFO]: Created: 8192x4096 textures-atlas
[05:25:23] [Realms Notification Availability checker #1/INFO]: Could not authorize you against Realms server: Invalid session id
[05:25:27] [Server thread/INFO]: Starting integrated minecraft server version 1.9.4
[05:25:27] [Server thread/INFO]: Generating keypair
[05:25:27] [Server thread/INFO] [FML]: Injecting existing block and item data into this server instance
[05:25:27] [Server thread/INFO] [FML]: Applying holder lookups
[05:25:27] [Server thread/INFO] [FML]: Holder lookups applied
[05:25:27] [Server thread/INFO] [FML]: Loading dimension 0 (Awrexsa) (net.minecraft.server.integrated.IntegratedServer@1997b715)
[05:25:27] [Server thread/INFO] [FML]: Loading dimension 1 (Awrexsa) (net.minecraft.server.integrated.IntegratedServer@1997b715)
[05:25:27] [Server thread/INFO] [FML]: Loading dimension -1 (Awrexsa) (net.minecraft.server.integrated.IntegratedServer@1997b715)
[05:25:27] [Server thread/INFO]: Preparing start region for level 0
[05:25:28] [Server thread/INFO]: Preparing spawn area: 40%
[05:25:29] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:713) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:611) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:148) ~[byl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:469) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_77]
Caused by: java.lang.ArithmeticException: / by zero
	at com.vanhal.progressiveautomation.entities.generator.TileGenerator.getBurnTime(TileGenerator.java:115) ~[TileGenerator.class:?]
	at com.vanhal.progressiveautomation.entities.BaseTileEntity.getBurnTime(BaseTileEntity.java:580) ~[BaseTileEntity.class:?]
	at com.vanhal.progressiveautomation.entities.BaseTileEntity.isFuel(BaseTileEntity.java:597) ~[BaseTileEntity.class:?]
	at com.vanhal.progressiveautomation.entities.BaseTileEntity.func_73660_a(BaseTileEntity.java:335) ~[BaseTileEntity.class:?]
	at com.vanhal.progressiveautomation.entities.generator.TileGenerator.func_73660_a(TileGenerator.java:59) ~[TileGenerator.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1797) ~[aht.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618) ~[lq.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:707) ~[MinecraftServer.class:?]
	... 4 more
[05:25:29] [Server thread/ERROR]: This crash report has been saved to: C:\Users\ADMIN\AppData\Roaming\.minecraft\crash-reports\crash-2016-05-29_05.25.29-server.txt
[05:25:29] [Server thread/INFO]: Stopping server
[05:25:29] [Server thread/INFO]: Saving players
[05:25:29] [Server thread/INFO]: Saving worlds
[05:25:29] [Server thread/INFO]: Saving chunks for level 'Awrexsa'/Overworld
[05:25:29] [Server thread/INFO]: Saving chunks for level 'Awrexsa'/Nether
[05:25:29] [Server thread/INFO]: Saving chunks for level 'Awrexsa'/The End
[05:25:30] [Server thread/INFO] [FML]: Unloading dimension 0
[05:25:30] [Server thread/INFO] [FML]: Unloading dimension -1
[05:25:30] [Server thread/INFO] [FML]: Unloading dimension 1
[05:25:30] [Server thread/INFO] [FML]: Applying holder lookups
[05:25:30] [Server thread/INFO] [FML]: Holder lookups applied
[05:25:30] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.
[05:25:30] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:557]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  FldLoadingPlugin (FastLeafDecay-MC1.9.4-1.7.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 29.05.16 05:25
Description: Ticking block entity

java.lang.ArithmeticException: / by zero
	at com.vanhal.progressiveautomation.entities.generator.TileGenerator.getBurnTime(TileGenerator.java:115)
	at com.vanhal.progressiveautomation.entities.BaseTileEntity.getBurnTime(BaseTileEntity.java:580)
	at com.vanhal.progressiveautomation.entities.BaseTileEntity.isFuel(BaseTileEntity.java:597)
	at com.vanhal.progressiveautomation.entities.BaseTileEntity.func_73660_a(BaseTileEntity.java:335)
	at com.vanhal.progressiveautomation.entities.generator.TileGenerator.func_73660_a(TileGenerator.java:59)
	at net.minecraft.world.World.func_72939_s(World.java:1797)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:707)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:611)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:148)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:469)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.vanhal.progressiveautomation.entities.generator.TileGenerator.getBurnTime(TileGenerator.java:115)
	at com.vanhal.progressiveautomation.entities.BaseTileEntity.getBurnTime(BaseTileEntity.java:580)
	at com.vanhal.progressiveautomation.entities.BaseTileEntity.isFuel(BaseTileEntity.java:597)
	at com.vanhal.progressiveautomation.entities.BaseTileEntity.func_73660_a(BaseTileEntity.java:335)
	at com.vanhal.progressiveautomation.entities.generator.TileGenerator.func_73660_a(TileGenerator.java:59)

-- Block entity being ticked --
Details:
	Name: TileGenerator // com.vanhal.progressiveautomation.entities.generator.TileGenerator
	Block type: ID #225 (tile.Generator // com.vanhal.progressiveautomation.blocks.BlockGenerator)
	Block data value: 5 / 0x5 / 0b0101
	Block location: World: (-36,62,117), Chunk: (at 12,3,5 in -3,7; contains blocks -48,0,112 to -33,255,127), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #225 (tile.Generator // com.vanhal.progressiveautomation.blocks.BlockGenerator)
	Actual block data value: 5 / 0x5 / 0b0101
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1797)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618)

-- Affected level --
Details:
	Level name: Awrexsa
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: 3794347803527086642
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-164,64,252), Chunk: (at 12,4,12 in -11,15; contains blocks -176,0,240 to -161,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 857005 game time, 391768 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 142491 (now: false), thunder time: 21320 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:707)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:611)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:148)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:469)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.9.4
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_77, Oracle Corporation
	Java VM Version: Java HotSp

Also, i cant play at this world. What can i do?

**Comment by Vanhal** [comment]
What is your fuelCost set to in your configs?

**Comment by Vanhal** [comment]
Hack added to work around this issue. "Fixed" in 1.10.2-1.6.49
