### ISSUE TITLE
[1.10.2]  Crash on game start: NoClassDefFoundError : ItemRFEngine 

### ISSUE THREAD

**Issue by PrinceOfAmber** [Vanhal/ProgressiveAutomation#262]
Crashlog is below.  I have no other mods that use RF engines, is that why?

---- Minecraft Crash Report ----

WARNING: coremods are present:
  AppleCore (AppleCore-mc1.10.2-1.3.5.jar)
  LoadingPlugin (Quark-beta-44.jar)
  LoadingPlugin (ChunkAnimator-MC1.9.4-1.2.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  BetterFoliageLoader (BetterFoliage-MC1.10-2.0.13.jar)
  dsurroundcore_unofficial (DynamicSurroundingsUnofficial-1.10.2-3.0.6.1BETA.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 16/07/16 9:44 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: com/vanhal/progressiveautomation/items/ItemRFEngine
    at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:186)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:562)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:216)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: com/vanhal/progressiveautomation/items/ItemRFEngine
    at com.vanhal.progressiveautomation.ProgressiveAutomation.<clinit>(ProgressiveAutomation.java:49)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:344)
    at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:485)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:235)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:213)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:531)
    ... 10 more
Caused by: java.lang.ClassNotFoundException: com.vanhal.progressiveautomation.items.ItemRFEngine
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 35 more
Caused by: java.lang.NoClassDefFoundError: cofh/api/energy/IEnergyContainerItem
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 37 more
Caused by: java.lang.ClassNotFoundException: cofh.api.energy.IEnergyContainerItem
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 41 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 128179432 bytes (122 MB) / 385916928 bytes (368 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.32 Powered by Forge 12.18.0.2010 Optifine OptiFine_1.10.2_HD_U_C2 44 mods loaded, 44 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UC  mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UC  FML{8.0.99.99} [Forge Mod Loader](forge-1.10.2-12.18.0.2010.jar) 
    UC  Forge{12.18.0.2010} [Minecraft Forge](forge-1.10.2-12.18.0.2010.jar) 
    UC  Ambience{GRADLE:VERSION-GRADLE:BUILD} [Ambience](Ambience 1.0-5.jar) 
    UC  lazAnvils{1.2.1.3} [Anvil Enchantments](anvils-1.10.2-1.2.1.3.jar) 
    UC  JEI{3.7.5.227} [Just Enough Items](jei_1.10.2-3.7.5.227.jar) 
    UC  AppleCore{1.3.5} [AppleCore](AppleCore-mc1.10.2-1.3.5.jar) 
    UC  betterbuilderswands{0.6.5} [Better Builder's Wands](BetterBuildersWands-0.6.5-1.10r138+8595fc7.jar) 
    UC  bettercombatmod{1.3.0} [Better Combat](BetterCombat-1.3.jar) 
    UC  BetterFoliage{2.0.13} [Better Foliage](BetterFoliage-MC1.10-2.0.13.jar) 
    UC  Chameleon{1.9.4-2.1.5} [Chameleon](Chameleon-1.10-2.1.5.jar) 
    UC  ChunkAnimator{1.2} [Chunk Animator](ChunkAnimator-MC1.9.4-1.2.jar) 
    UC  combathelp{1.0.3} [Combat Help](combathelp-1.9.4-1.0.3.jar) 
    UC  cyclicmagic{1.4.0} [Cyclic](Cyclic-1.10.2-1.4.0.jar) 
    UC  Ding{MC1.9.0v2} [Ding](Ding-1.10.2-1.0.0.jar) 
    UC  dsurroundunofficial{3.0.6.1BETA} [Dynamic Surroundings Unofficial](DynamicSurroundingsUnofficial-1.10.2-3.0.6.1BETA.jar) 
    UC  EnderZoo{1.10-1.2.3.43} [Ender Zoo](EnderZoo-1.10-1.2.3.43.jar) 
    UC  FastLeaveDecay{1.1} [Fast Leave Decay](FastLeaveDecay-MC1.10-1.2.1.jar) 
    UC  forgecreeperheal{1.3.0} [Forge Creeper Heal](forgecreeperheal-1.10.2-1.3.0.jar) 
    UC  GlobalGameRules{1.0} [Global GameRules](GlobalGameRules-1.10.2-1.0.jar) 
    UC  grapple_hooks{1.0.8} [Grapple Hooks](GrappleHooks-1.10-1.0.8.jar) 
    UC  gravestone{1.5.0} [Gravestone](Gravestone Mod 1.5.0.jar) 
    UC  HoloInventory{2.0.1.135} [HoloInventory](HoloInventory-1.9.4-2.0.1.135.jar) 
    UC  inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks](InventoryTweaks-1.61-58.jar) 
    UC  journeymap{1.10.2-5.2.4} [JourneyMap](journeymap-1.10.2-5.2.4-unlimited.jar) 
    UC  jeresources{0.4.6.41} [Just Enough Resources](JustEnoughResources-1.10.2-0.4.6.41.jar) 
    UC  kleeslabs{3.3.1} [KleeSlabs](KleeSlabs-mc1.10-3.3.1.jar) 
    UC  LunatriusCore{1.1.2.36} [LunatriusCore](LunatriusCore-1.10.2-1.1.2.36-universal.jar) 
    UC  LaserLevel{2.1.0.13} [Laser Level](LaserLevel-1.10.2-2.1.0.13-universal.jar) 
    UC  lteleporters{1.1.3} [Lemon's Simple Teleporters](LemonsTeleporters-1.1.3.jar) 
    UC  ModLister{1.10-2.1.6} [ModLister](ModLister-1.10-2.1.6.jar) 
    UC  Neat{GRADLE:VERSION-GRADLE:BUILD} [Neat](Neat 1.3-10.jar) 
    UE  notenoughwands{1.3.5} [Not Enough Wands](notenoughwands-1.9.4-1.3.5.jar) 
    UE  progressiveautomation{1.6.48} [Progressive Automation](ProgressiveAutomation-1.10.2-1.6.48.jar) 
    UC  Quark{beta-44} [Quark](Quark-beta-44.jar) 
    UC  reptilemod{3.5.2} [Reptile Mod](reptilemod-1.10.2-3.5.2-55.jar) 
    UC  Schematica{1.7.8.150} [Schematica](Schematica-1.10.2-1.7.8.150-universal.jar) 
    UC  soundfilters{0.9_for_1.9} [Sound Filters](SoundFilters-0.9_for_1.10.jar) 
    UC  Stackie{1.6.0.44} [Stackie](Stackie-1.10.2-1.6.0.44-universal.jar) 
    UC  StorageDrawers{1.9.4-3.1.11} [Storage Drawers](StorageDrawers-1.10-3.1.11.jar) 
    UC  supercraftingframe{1.2.0.85} [Super Crafting Frame](supercraftingframe-1.10.2-1.2.0.85.jar) 
    UC  VeinMiner{0.34.1_1.9-73be663} [Vein Miner](VeinMiner-0.34.1-1.9r571+73be663.jar) 
    UC  VeinMinerModSupport{0.34.1_1.9-73be663} [Mod Support](VeinMiner-0.34.1-1.9r571+73be663.jar) 
    UC  vc{v0.2.9b-mc1.10.2} [ViesCraft](ViesCraft-0.2.9b-mc1.10.2.jar) 
    Loaded coremods (and transformers): 
AppleCore (AppleCore-mc1.10.2-1.3.5.jar)
  squeek.applecore.asm.TransformerModuleHandler
LoadingPlugin (Quark-beta-44.jar)
  vazkii.quark.base.asm.ClassTransformer
LoadingPlugin (ChunkAnimator-MC1.9.4-1.2.jar)
  lumien.chunkanimator.asm.ClassTransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
BetterFoliageLoader (BetterFoliage-MC1.10-2.0.13.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
dsurroundcore_unofficial (DynamicSurroundingsUnofficial-1.10.2-3.0.6.1BETA.jar)
  org.blockartistry.mod.DynSurround.asm.Transformer
    GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4276' Renderer: 'Intel(R) HD Graphics'
    OptiFine Version: OptiFine_1.10.2_HD_U_C2
    Render Distance Chunks: 8
    Mipmaps: 4
    Anisotropic Filtering: 1
    Antialiasing: 0
    Multitexture: false
    Shaders: null
    OpenGlVersion: 4.0.0 - Build 10.18.10.4276
    OpenGlRenderer: Intel(R) HD Graphics
    OpenGlVendor: Intel
    CpuCount: 4

**Comment by Vanhal** [comment]
I have no idea why this would happen. Only thing I can think of is that another mod is overriding my class or possibly the RF lib.... But from the looks of it nothing else is using the RF lib in your pack....

Does it work without optifine?
