### ISSUE TITLE
1.9.4 RFE engine chrash on startup

### ISSUE THREAD

**Issue by yannik603** [Vanhal/ProgressiveAutomation#267]
---- Minecraft Crash Report ----
// Don't do that.

Time: 7/24/16 9:58 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: com/vanhal/progressiveautomation/items/ItemRFEngine
    at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:179)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:555)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:210)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:437)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: com/vanhal/progressiveautomation/items/ItemRFEngine
    at com.vanhal.progressiveautomation.ProgressiveAutomation.<clinit>(ProgressiveAutomation.java:49)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:344)
    at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:474)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:228)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:206)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:524)
    ... 10 more
Caused by: java.lang.ClassNotFoundException: com.vanhal.progressiveautomation.items.ItemRFEngine
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 36 more
Caused by: java.lang.NoClassDefFoundError: cofh/api/energy/IEnergyContainerItem
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 38 more
Caused by: java.lang.ClassNotFoundException: cofh.api.energy.IEnergyContainerItem
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 42 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.9.4
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 161575136 bytes (154 MB) / 358617088 bytes (342 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.28 Powered by Forge 12.17.0.1976 13 mods loaded, 13 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UC  mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UC  FML{8.0.99.99} [Forge Mod Loader](forge-1.9.4-12.17.0.1976.jar) 
    UC  Forge{12.17.0.1976} [Minecraft Forge](forge-1.9.4-12.17.0.1976.jar) 
    UC  Chameleon{1.9.4-2.1.6} [Chameleon](Chameleon-1.9.4-2.1.6.jar) 
    UC  guideBook{1.6} [Guide Book](GuideBook-1.9.4-1.6a.jar) 
    UC  journeymap{1.9.4-5.2.3} [JourneyMap](journeymap-1.9.4-5.2.3-unlimited.jar) 
    UC  mantle{1.9.4-0.10.2.jenkins149} [Mantle](Mantle-1.9.4-0.10.2.jar) 
    UE  notenoughwands{1.3.5} [Not Enough Wands](notenoughwands-1.9.4-1.3.5.jar) 
    UE  progressiveautomation{1.6.47} [Progressive Automation](ProgressiveAutomation-1.9.4-1.6.47.jar) 
    UC  StorageDrawers{1.9.4-3.2.1} [Storage Drawers](StorageDrawers-1.9.4-3.2.1.jar) 
    UC  tconstruct{1.9.4-2.3.3.jenkins263} [Tinkers' Construct](TConstruct-1.9.4-2.3.3.jar) 
    UC  chunkbase_villageinfo_ssp{2.1} [Village Info (SSP)](VillageInfoSSP-1.9.4-2.1.jar) 
    UC  Waila{1.7.0} [Waila](Waila-1.7.0-B3_1.9.4.jar) 
    Loaded coremods (and transformers): 
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 358.91' Renderer: 'GeForce GTX 650/PCIe/SSE2'
    Pulsar/tconstruct loaded Pulses: 
        - TinkerCommons (Enabled/Forced)
        - TinkerWorld (Enabled/Not Forced)
        - TinkerTools (Enabled/Not Forced)
        - TinkerSmeltery (Enabled/Not Forced)
        - TinkerGadgets (Enabled/Not Forced)
        - TinkerOredict (Enabled/Forced)
        - TinkerIntegration (Enabled/Forced)
        - TinkerFluids (Enabled/Forced)
        - TinkerMaterials (Enabled/Forced)
        - WailaIntegration (Enabled/Not Forced)

**Comment by yannik603** [comment]
version 1.9.4 - 1.6.47

**Comment by yannik603** [comment]
can someone help me fix this , I love this mod but I cant play it.

**Comment by yannik603** [comment]
I fixed it by removing the mod notenoughwands , aparently they werent compatible.
