### ISSUE TITLE
Miner crash w/TConstruct pick

### ISSUE THREAD

**Issue by gdude2002** [Vanhal/ProgressiveAutomation#278]
```
net.minecraft.util.ReportedException: Ticking block entity
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:715) ~[MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) ~[ld.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) ~[MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
at slimeknights.tconstruct.library.tools.DualToolHarvestUtils.shouldUseOffhand(DualToolHarvestUtils.java:26) ~[DualToolHarvestUtils.class:?]
at slimeknights.tconstruct.library.tools.TinkerToolCore.getHarvestLevel(TinkerToolCore.java:56) ~[TinkerToolCore.class:?]
at net.minecraftforge.common.ForgeHooks.canToolHarvestBlock(ForgeHooks.java:187) ~[ForgeHooks.class:?]
at com.vanhal.progressiveautomation.entities.miner.TileMiner.canMineBlock(TileMiner.java:131) ~[TileMiner.class:?]
at com.vanhal.progressiveautomation.entities.miner.TileMiner.scanBlocks(TileMiner.java:90) ~[TileMiner.class:?]
at com.vanhal.progressiveautomation.entities.miner.TileMiner.checkForChanges(TileMiner.java:428) ~[TileMiner.class:?]
at com.vanhal.progressiveautomation.entities.miner.TileMiner.func_73660_a(TileMiner.java:67) ~[TileMiner.class:?]
at net.minecraft.world.World.func_72939_s(World.java:1804) ~[aid.class:?]
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619) ~[ls.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) ~[MinecraftServer.class:?]
... 4 more
```

Forge: 12.18.1.2094
MC: 1.10.2
PA: 1.6.51

---

Happened right after I stuck a TConstruct pick into my iron miner, replacing a stone one that was already in there.

**Comment by MikeSingularity** [comment]
This is a bug in Tinkers' Construct that was fixed two days ago, see https://github.com/SlimeKnights/TinkersConstruct/issues/2409  It doesn't look like there's an official update with the change just yet.

**Comment by ProsperCraft** [comment]
http://pastebin.com/TrGDXGMr

Is this the same?

**Comment by gdude2002** [comment]
@ProsperCraft No, that looks to be a different error.

@MikeSingularity Thanks, still waiting for that one to make a release.
