### ISSUE TITLE
Progressive Automation Crash with Agricraft

### ISSUE THREAD

**Issue by starryknight64** [Vanhal/ProgressiveAutomation#370]
Crash happens when placing a block of gravel on top of a planter (planter has coal, hoe, and a stack of Agricraft aurigold seeds in it) and then placing Agricraft crop sticks on top of the gravel. Obviously, it's not a valid growth setup for the aurigold seeds. Just didn't expect it to crash the Minecraft client itself.

I've attached the below logs as well as my config files for both Progressive Automation and Agricraft.

```
The game crashed whilst ticking block entity
The game crashed whilst ticking block entity
Error: java.lang.IllegalArgumentException: Invalid hand null
```

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  Quark Plugin (Quark-r1.5-154.jar)
Contact their authors BEFORE contacting forge

// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 5/29/19 11:59 AM
Description: Ticking block entity

java.lang.IllegalArgumentException: Invalid hand null
	at net.minecraft.entity.EntityLivingBase.func_184586_b(EntityLivingBase.java:1640)
	at com.infinityraider.agricraft.blocks.BlockCrop.func_180639_a(BlockCrop.java:106)
	at com.vanhal.progressiveautomation.common.compat.mods.RightClick.harvestPlant(RightClick.java:40)
	at com.vanhal.progressiveautomation.common.compat.ModHelper.harvestPlant(ModHelper.java:139)
	at com.vanhal.progressiveautomation.common.entities.planter.TilePlanter.harvestPlant(TilePlanter.java:145)
	at com.vanhal.progressiveautomation.common.entities.planter.TilePlanter.func_73660_a(TilePlanter.java:66)
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.entity.EntityLivingBase.func_184586_b(EntityLivingBase.java:1640)
	at com.infinityraider.agricraft.blocks.BlockCrop.func_180639_a(BlockCrop.java:106)
	at com.vanhal.progressiveautomation.common.compat.mods.RightClick.harvestPlant(RightClick.java:40)
	at com.vanhal.progressiveautomation.common.compat.ModHelper.harvestPlant(ModHelper.java:139)
	at com.vanhal.progressiveautomation.common.entities.planter.TilePlanter.harvestPlant(TilePlanter.java:145)
	at com.vanhal.progressiveautomation.common.entities.planter.TilePlanter.func_73660_a(TilePlanter.java:66)

-- Block entity being ticked --
Details:
	Name: progressiveautomation:tile_planter_diamond // com.vanhal.progressiveautomation.common.entities.planter.TilePlanterDiamond
	Block type: ID #1118 (tile.progressiveautomation:planter_diamond // com.vanhal.progressiveautomation.common.blocks.BlockPlanter // progressiveautomation:planter_diamond)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-131,91,336), Chunk: (at 13,5,0 in -9,21; contains blocks -144,0,336 to -129,255,351), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #1118 (tile.progressiveautomation:planter_diamond // com.vanhal.progressiveautomation.common.blocks.BlockPlanter // progressiveautomation:planter_diamond)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: Testing 2
	All players: 1 total; [EntityPlayerMP['starryknight64'/128, l='Testing 2', x=-128.70, y=92.00, z=337.30]]
	Chunk stats: ServerChunkCache: 686 Drop: 0
	Level seed: 8352464459630466831
	Level generator: ID 07 - ultra_space, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (4,64,256), Chunk: (at 4,4,0 in 0,16; contains blocks 0,0,256 to 15,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 17028 game time, 34691 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 48201 (now: false), thunder time: 92303 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 986214768 bytes (940 MB) / 3638034432 bytes (3469 MB) up to 6681526272 bytes (6372 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx7168m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 86
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 Optifine OptiFine_1.12.2_HD_U_E3 45 mods loaded, 45 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                    | Version                  | Source                                          | Signature                                |
	|:------ |:--------------------- |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft             | 1.12.2                   | minecraft.jar                                   | None                                     |
	| LCHIJA | mcp                   | 9.42                     | minecraft.jar                                   | None                                     |
	| LCHIJA | FML                   | 8.0.99.99                | forge-1.12.2-14.23.5.2838.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                 | 14.23.5.2838             | forge-1.12.2-14.23.5.2838.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | infinitylib           | 1.12.2-1.12.0            | infinitylib-1.12.0.jar                          | None                                     |
	| LCHIJA | agricraft             | 2.12.0-1.12.0-a6         | AgriCraft-2.12.0-1.12.0-a6.jar                  | None                                     |
	| LCHIJA | autocrafter           | 4.3                      | autocrafter-4.3.jar                             | None                                     |
	| LCHIJA | jei                   | 4.15.0.268               | jei_1.12.2-4.15.0.268.jar                       | None                                     |
	| LCHIJA | quark                 | r1.5-154                 | Quark-r1.5-154.jar                              | None                                     |
	| LCHIJA | autoreglib            | 1.3-30                   | AutoRegLib-1.3-30.jar                           | None                                     |
	| LCHIJA | betterbuilderswands   | 0.11.1                   | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar | None                                     |
	| LCHIJA | biomesoplenty         | 7.0.1.2439               | BiomesOPlenty-1.12.2-7.0.1.2439-universal.jar   | None                                     |
	| LCHIJA | bonsaitrees           | 1.1.2                    | bonsaitrees-1.1.2-b144.jar                      | None                                     |
	| LCHIJA | chameleon             | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                        | None                                     |
	| LCHIJA | codechickenlib        | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | controlling           | 3.0.6                    | Controlling-3.0.6.jar                           | None                                     |
	| LCHIJA | cookingforblockheads  | 6.4.70                   | CookingForBlockheads_1.12.2-6.4.70.jar          | None                                     |
	| LCHIJA | diethopper            | 1.1                      | diethopper-1.1.jar                              | None                                     |
	| LCHIJA | enderstorage          | 2.4.5.135                | EnderStorage-1.12.2-2.4.5.135-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | fastleafdecay         | v14                      | FastLeafDecay-v14.jar                           | None                                     |
	| LCHIJA | ftblib                | 5.4.1.99                 | FTBLib-5.4.1.99.jar                             | None                                     |
	| LCHIJA | ftbutilities          | 5.4.0.96                 | FTBUtilities-5.4.0.96.jar                       | None                                     |
	| LCHIJA | ftbbackups            | 0.0.0.ftbbackups         | FTBUtilitiesBackups-1.0.0.4.jar                 | None                                     |
	| LCHIJA | pixelmon              | 7.0.6                    | Pixelmon-1.12.2-7.0.6-universal.jar             | None                                     |
	| LCHIJA | apricorns             | 2.0.0                    | Growable Apricorns-2.0.0.jar                    | None                                     |
	| LCHIJA | harvest               | 1.12-1.2.7-20            | Harvest-1.12-1.2.7-20.jar                       | None                                     |
	| LCHIJA | dcs_dispenser         | 1.0.3                    | HarvestWithDispenser-1.12.2-1.0.3.jar           | None                                     |
	| LCHIJA | wasaila               | 1.0                      | Wasaila-1.0.jar                                 | None                                     |
	| LCHIJA | waila                 | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                     | None                                     |
	| LCHIJA | inventorytweaks       | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                        | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | ironbackpacks         | 1.12.2-3.0.8-12          | IronBackpacks-1.12.2-3.0.8-12.jar               | None                                     |
	| LCHIJA | journeymap            | 1.12.2-5.5.4             | journeymap-1.12.2-5.5.4.jar                     | None                                     |
	| LCHIJA | keepinginventory      | 2.4                      | KeepingInventory-1.12.2-2.4.jar                 | None                                     |
	| LCHIJA | morpheus              | 1.12.2-3.5.106           | Morpheus-1.12.2-3.5.106.jar                     | None                                     |
	| LCHIJA | mousetweaks           | 2.10                     | MouseTweaks-2.10-mc1.12.2.jar                   | None                                     |
	| LCHIJA | oreexcavation         | 1.4.140                  | OreExcavation-1.4.140.jar                       | None                                     |
	| LCHIJA | pixelextras           | 2.4.7                    | PixelExtras-1.12.2-2.4.7-universal.jar          | None                                     |
	| LCHIJA | pixelmoninformation   | 0.3.1                    | PixelmonInformation-1.12.2-7.0.0-0.3.1.jar      | None                                     |
	| LCHIJA | progressiveautomation | 1.7.8                    | ProgressiveAutomation-1.12.2-1.7.8.jar          | None                                     |
	| LCHIJA | quarkoddities         | 1                        | QuarkOddities-1.12.2.jar                        | None                                     |
	| LCHIJA | storagenetwork        | 1.7.4                    | SimpleStorageNetwork-1.12.2-1.7.4.jar           | 1bc8f8dbe770187a854cef35dad0ff40ba441bbe |
	| LCHIJA | storagedrawers        | 1.12-5.3.5               | StorageDrawers-1.12.2-5.3.8.jar                 | None                                     |
	| LCHIJA | storagedrawersextra   | @VERSION@                | StorageDrawersExtras-1.12-3.1.0.jar             | None                                     |
	| LCHIJA | wailaharvestability   | 1.1.12                   | WailaHarvestability-mc1.12-1.1.12.jar           | None                                     |
	| LCHIJA | reauth                | 3.6.0                    | reauth-3.6.0.jar                                | daba0ec4df71b6da841768c49fb873def208a1e3 |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
Quark Plugin (Quark-r1.5-154.jar)
  vazkii.quark.base.asm.ClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['starryknight64'/128, l='Testing 2', x=-128.70, y=92.00, z=337.30]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 416.34
	OpenGlRenderer: GeForce GTX 750 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4
```

[logs and config.zip](https://github.com/Vanhal/ProgressiveAutomation/files/3233642/logs.and.config.zip)

**Comment by starryknight64** [comment]
I've also tried this with a normal configuration of gold ore with gravel on top beside the planter with a range upgrade and it also crashes in the same way. Same error, same line numbers in the stack trace.
